
workspace 'CamSua.xcworkspace'

platform :ios, '10.0'
use_modular_headers!
use_frameworks!
# ignore all warnings from all dependencies
inhibit_all_warnings!


def share_pods
    pod 'SnapKit', '4.2.0'
end

# ---------- Core Framework & Core Example ---------- //
target 'CamSuaCore' do
    project 'CamSuaCore/CamSuaCore.xcodeproj'
    share_pods
end


